### PR TITLE
Add Magma dashboard

### PR DESCRIPTION
**Pull request by rohansuri**
Hi @dave-finlay, wanted to add this dashboard for Magma.

### CODE REVIEW

**Comment by rohansuri** [comment]
Seems this dashboard has some issue. I'll fix it and push a new commit.

> rohansuri@apples-MacBook-Pro singlenodeload % promtimer
extracting stats, couchbase.log from cbcollect zip:singlenodeload.zip
using grafana home path:/usr/local/share/grafana 
Traceback (most recent call last):
  File "/Users/rohansuri/cb/promtimer/bin/../promtimer/promtimer.py", line 308, in <module>
    main()
  File "/Users/rohansuri/cb/promtimer/bin/../promtimer/promtimer.py", line 279, in main
    prepare_grafana(grafana_port,
  File "/Users/rohansuri/cb/promtimer/bin/../promtimer/promtimer.py", line 150, in prepare_grafana
    make_dashboards(stats_sources, buckets, min_time_string, max_time_string, refresh)
  File "/Users/rohansuri/cb/promtimer/bin/../promtimer/promtimer.py", line 102, in make_dashboards
    dash = dashboard.make_dashboard(meta,
  File "/Users/rohansuri/cb/promtimer/promtimer/dashboard.py", line 176, in make_dashboard
    template_string = get_template(dashboard_meta['_base'])
KeyError: '_base'

**Comment by rohansuri** [comment]
Ah so there's some transformation required on the native Grafana dashboards before Promtimer can parse it. I'll do it.

**Comment by dave-finlay** [comment]
Yes. I'd suggest you start with one of the existing dashboards, remove all the panels and then begin adding the panels that you want. You should decide if you want a global dashboard (covering all nodes e.g. cluster-overview), a per-node dashboard (e.g. node-overview) a per-bucket dashboard (e.g. bucket-overview) or a node and bucket dashboard (e.g. kv-nodebucket).

**Comment by rohansuri** [comment]
Thanks for the suggestion, let me do that.

**Comment by rohansuri** [comment]
> Yes. I'd suggest you start with one of the existing dashboards, remove all the panels and then begin adding the panels that you want.

This didn't work. Looks like exporting a dashboard from Grafana changes its field names again which is incompatible with Promtimer. Had to manually change some field names.  

I've prepared the dashboard as per the Promtimer format. It is loading fine for me locally. Please take a look @dave-finlay.

**Comment by dave-finlay** [comment]
Hi @rohansuri:

Due to the pre-processing that Promtimer does on dashboards (like expanding buckets and data-sources) it's not possible to directly use Grafana dashboards. In addition, one of the ideas in Promtimer is to keep the dashboard boilerplate to a minimum. The way this is done is with templates. So, for instance the panel template (in templates/panel.json) includes a lot of boilerplate that I don't want to repeat everywhere. This achieves 2 things: (1) it make the dashboards more readable and (2) it means that a change to the underlying panel will result in a change to every dashbaord. (This is useful, for instance, when we moved to used "timeseries" panels by default - which are better - late last year.

In any case, I converted 2 of your panels -- the first two -- in this pull request, which I built on top your PR: https://github.com/couchbaselabs/promtimer/pull/46. 

E.g. the first panel with all the boilerplate removed looks as below. It just includes the stuff that's needed: the title, the height (12 is the default), the data source and the targets. The second panel is similarly simpler. At least in my view this is preferable. Would you mind converting the remaining panels in this dashboard similarly?

```
    {
      "_base": "panel",
      "datasource": "${node}",
      "title": "OPS rate",
      "gridPos": {
        "h": 9
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "fillOpacity": 5
          }
        }
      },
      "_targets": [
        {
          "_base": "target",
          "expr": "rate(kv_ep_magma_gets{bucket=\"$bucket\"}[20s])",
          "legendFormat": "gets",
          "refId": "A"
        },
        {
          "_base": "target",
          "expr": "rate(kv_ep_magma_sets{bucket=\"$bucket\"}[20s])",
          "legendFormat": "sets",
          "refId": "E"
        },
        {
          "_base": "target",
          "expr": "rate(kv_ep_magma_inserts{bucket=\"$bucket\"}[20s])",
          "legendFormat": "inserts",
          "refId": "B"
        }
      ]
```

**Comment by rohansuri** [comment]
@dave-finlay thanks for the guidance, wasn't aware of the Promtimer dashboarding model. I've converted all panels to what you suggested. Please take another look. Thanks!

**Comment by dave-finlay** [comment]
Hey Rohan - 

Looks great. I like your use of the calculated fields in the Block Cache graph. Thanks for submitting a dashboard!

**Pull request merged**
